version: '3.8'

services:
  signa-chatbot:
    build: .
    container_name: signa-chatbot
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - DEBUG_MODE=${DEBUG_MODE:-True}
      - CRAWL_TIMEOUT=${CRAWL_TIMEOUT:-30}
      - MAX_RETRIES=${MAX_RETRIES:-3}
      - CACHE_ENABLED=${CACHE_ENABLED:-True}
      - CACHE_TTL=${CACHE_TTL:-3600}
    volumes:
      - ./knowledge_base.pkl:/app/knowledge_base.pkl
    stdin_open: true
    tty: true